FROM ubuntu:22.10

# debian 更换软件安装源
# RUN sed -i 's@http://deb.debian.org@http://mirrors.aliyun.com@g' /etc/apt/sources.list

# ubuntu 更换软件安装源 https://blog.csdn.net/qq_56778331/article/details/126916525

RUN apt-get update -y && \
    apt-get -y install gcc make vim wget curl composer php



