version: "3"

services:
  php73:
    build:
      context: ./
      dockerfile: Dockerfile
    #depends_on:
      #- redis
    hostname: php73
    container_name: php73
    volumes:
      - ./configs:/cfgs
    env_file: .env

  #redis:
    #image: redis:latest
