version: "3"
services:
  php7.2:
    container_name: php7.2
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/ovim/php:7.2-fpm
    volumes:
      - ../../wwwroot:/wwwroot:rw
      - ./configs/php.ini:/usr/local/etc/php/php.ini:rw
      - ./configs/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
    networks:
      default:
        ipv4_address: ${PHP72_IP}
networks:
  default:
    name: dev_enviroment
