version: "3"

services:
  php74:
    build:
      context: ./
      dockerfile: Dockerfile
#    depends_on:
#      - redis
    hostname: php74
    container_name: php74
    volumes:
      - ./configs:/cfgs
    env_file: .env

#  redis:
#    image: redis:latest
