version: "3"
services:
  nginx:
    # env_file:
    #   - ../.env
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    # build:
    #   context: ./
    #   args:
    #     - NGINX_VER=1.17
    restart: always
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./log/:/var/log/nginx/:rw
      - ./conf/vhost/:/etc/nginx/conf.d/:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ${PROJECT_PATH}:/wwwroot/:rw
    networks:
      default:
        ipv4_address: ${NGINX_IP}
networks:
  default:
    name: dev_enviroment