version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ../../../services/nginx
      args:
        - NGINX_VER=1.17
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../../../logs/nginx:/var/log/nginx:rw
      - ../../../services/nginx/conf.d:/etc/nginx/conf.d:rw
      - ../../../wwwroot:/wwwroot:rw
      - ../../../services/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    networks:
      dev:
        ipv4_address: 172.19.0.2

  php74:
    container_name: php74
    build:
      context: ../../../services/php/php74
      args:
        - PHP_VER=7.4-fpm # php版本
    restart: always
    depends_on:
      - nginx
    volumes:
      - ../../../wwwroot:/wwwroot:rw
      - ../../../services/php/php74/php.ini:/usr/local/etc/php/php.ini:rw
      - ../../../services/php/php74/conf.d:/usr/local/etc/php/conf.d:rw
    networks:
      dev:
        ipv4_address: 172.19.0.10

  php70:
    container_name: php70
    build:
      context: ../../../services/php/php70
      args:
        - PHP_VER=7.0-fpm # php版本
    restart: always
    depends_on:
      - nginx
    volumes:
      - ../../../wwwroot:/wwwroot:rw
      - ../../../services/php/php70/php.ini:/usr/local/etc/php/php.ini:rw
      - ../../../services/php/php70/conf.d:/usr/local/etc/php/conf.d:rw
    networks:
      dev:
        ipv4_address: 172.19.0.11


  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    depends_on:
      - php74
      - php70
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      # - ./services/mysql/conf:/etc/mysql  
      - ../../../data/mysql/data:/var/lib/mysql:rw
    networks:
      dev:
        ipv4_address: 172.19.0.20


networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
