version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    # 将在哪个平台上执行服务的构建
    # platform: linux/x86_64
    restart: always
    command: >
      bash -c "
      chmod 644 /etc/mysql/conf.d/*
      && /entrypoint.sh mysqld
      "
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./conf.d/:/etc/mysql/conf.d/:rw
      - ./log/:/var/lib/mysql-logs/:rw
      - ./data/:/var/lib/mysql/:rw
    networks:
      default:
        ipv4_address: ${MYSQL_IP}
networks:
  default:
    name: dev_enviroment