version: "3"
services:
  redis:
    container_name: redis
    build:
      context: ./
      args:
        - REDIS_VER=5
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ../../data/redis:/data:rw
      - ../../logs/redis:/var/log/:rw
    restart: always
